### PR TITLE
Avoid divide by zero error

### PR DESCRIPTION
**Pull request by kirito25**
Added a small offset to prevent divide by error

### CODE REVIEW

**Comment by Michiele** [comment]
I have been trying to figure this out for a while and I still don't get it. Why are some runs of the network giving us all negative results? My implementation of run_experiment keeps classifying everything as non crater. Are you getting the same results in yours? I tried looking up the way argmax() works and it seems fine. I understand the fix here but I don't think its a good sign that the network classifies everything as 0.

**Comment by EvanDonato** [comment]
We are going to look at it again after the meeting.  We fixed it so it should doing an equal distribution of crater and non-crater based on a user defined ratio but it still occasionally has sets that have only non-craters.  This is not intended at this point.  It was unforeseen before.

**Comment by Michiele** [comment]
oh I see. I thought that was caused by the network. That should be easy to deal with then.

**Comment by EvanDonato** [comment]
To be clear it is because the non-crater set is huge compared to the crater set.

**Comment by Michiele** [comment]
I still have a few questions about this but lets go over it in the meeting.

**Pull request merged**
